 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/consultations", type: :request do
  
  # Consultation. As you add validations to Consultation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Consultation.create! valid_attributes
      get consultations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      consultation = Consultation.create! valid_attributes
      get consultation_url(consultation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_consultation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      consultation = Consultation.create! valid_attributes
      get edit_consultation_url(consultation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Consultation" do
        expect {
          post consultations_url, params: { consultation: valid_attributes }
        }.to change(Consultation, :count).by(1)
      end

      it "redirects to the created consultation" do
        post consultations_url, params: { consultation: valid_attributes }
        expect(response).to redirect_to(consultation_url(Consultation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Consultation" do
        expect {
          post consultations_url, params: { consultation: invalid_attributes }
        }.to change(Consultation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post consultations_url, params: { consultation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested consultation" do
        consultation = Consultation.create! valid_attributes
        patch consultation_url(consultation), params: { consultation: new_attributes }
        consultation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the consultation" do
        consultation = Consultation.create! valid_attributes
        patch consultation_url(consultation), params: { consultation: new_attributes }
        consultation.reload
        expect(response).to redirect_to(consultation_url(consultation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        consultation = Consultation.create! valid_attributes
        patch consultation_url(consultation), params: { consultation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested consultation" do
      consultation = Consultation.create! valid_attributes
      expect {
        delete consultation_url(consultation)
      }.to change(Consultation, :count).by(-1)
    end

    it "redirects to the consultations list" do
      consultation = Consultation.create! valid_attributes
      delete consultation_url(consultation)
      expect(response).to redirect_to(consultations_url)
    end
  end
end
